CRITICAL - 2022-06-30 14:58:27 --> Trying to access array offset on value of type null
#0 D:\DFPYME\htdocs\dfpyme\app\Controllers\pedido\pedidoController.php(1165): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Trying to acces...', 'D:\\DFPYME\\htdoc...', 1165)
#1 D:\DFPYME\htdocs\dfpyme\system\CodeIgniter.php(832): App\Controllers\pedido\pedidoController->valor_pedido()
#2 D:\DFPYME\htdocs\dfpyme\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\pedido\pedidoController))
#3 D:\DFPYME\htdocs\dfpyme\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 D:\DFPYME\htdocs\dfpyme\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-06-30 14:58:28 --> Trying to access array offset on value of type null
#0 D:\DFPYME\htdocs\dfpyme\app\Controllers\pedido\pedidoController.php(1165): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Trying to acces...', 'D:\\DFPYME\\htdoc...', 1165)
#1 D:\DFPYME\htdocs\dfpyme\system\CodeIgniter.php(832): App\Controllers\pedido\pedidoController->valor_pedido()
#2 D:\DFPYME\htdocs\dfpyme\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\pedido\pedidoController))
#3 D:\DFPYME\htdocs\dfpyme\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 D:\DFPYME\htdocs\dfpyme\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-06-30 14:58:29 --> Trying to access array offset on value of type null
#0 D:\DFPYME\htdocs\dfpyme\app\Controllers\pedido\pedidoController.php(1165): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Trying to acces...', 'D:\\DFPYME\\htdoc...', 1165)
#1 D:\DFPYME\htdocs\dfpyme\system\CodeIgniter.php(832): App\Controllers\pedido\pedidoController->valor_pedido()
#2 D:\DFPYME\htdocs\dfpyme\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\pedido\pedidoController))
#3 D:\DFPYME\htdocs\dfpyme\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 D:\DFPYME\htdocs\dfpyme\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-06-30 14:58:30 --> Trying to access array offset on value of type null
#0 D:\DFPYME\htdocs\dfpyme\app\Controllers\pedido\pedidoController.php(1165): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Trying to acces...', 'D:\\DFPYME\\htdoc...', 1165)
#1 D:\DFPYME\htdocs\dfpyme\system\CodeIgniter.php(832): App\Controllers\pedido\pedidoController->valor_pedido()
#2 D:\DFPYME\htdocs\dfpyme\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\pedido\pedidoController))
#3 D:\DFPYME\htdocs\dfpyme\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 D:\DFPYME\htdocs\dfpyme\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-06-30 14:58:34 --> Trying to access array offset on value of type null
#0 D:\DFPYME\htdocs\dfpyme\app\Controllers\pedido\pedidoController.php(1165): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Trying to acces...', 'D:\\DFPYME\\htdoc...', 1165)
#1 D:\DFPYME\htdocs\dfpyme\system\CodeIgniter.php(832): App\Controllers\pedido\pedidoController->valor_pedido()
#2 D:\DFPYME\htdocs\dfpyme\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\pedido\pedidoController))
#3 D:\DFPYME\htdocs\dfpyme\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 D:\DFPYME\htdocs\dfpyme\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-06-30 14:58:34 --> Trying to access array offset on value of type null
#0 D:\DFPYME\htdocs\dfpyme\app\Controllers\pedido\pedidoController.php(1165): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Trying to acces...', 'D:\\DFPYME\\htdoc...', 1165)
#1 D:\DFPYME\htdocs\dfpyme\system\CodeIgniter.php(832): App\Controllers\pedido\pedidoController->valor_pedido()
#2 D:\DFPYME\htdocs\dfpyme\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\pedido\pedidoController))
#3 D:\DFPYME\htdocs\dfpyme\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 D:\DFPYME\htdocs\dfpyme\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
ERROR - 2022-06-30 19:17:37 --> ErrorException: pg_query(): Query failed: ERROR:  la sintaxis de entrada no es válida para tipo date: «»
LINE 10:         fecha_factura_venta BETWEEN '2022-06-30' AND '';
                                                              ^ in D:\DFPYME\htdocs\dfpyme\system\Database\Postgre\Connection.php:135
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'D:\\DFPYME\\htdoc...', 135)
#1 D:\DFPYME\htdocs\dfpyme\system\Database\Postgre\Connection.php(135): pg_query(Resource id #122, '\r\n        SELEC...')
#2 D:\DFPYME\htdocs\dfpyme\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('\r\n        SELEC...')
#3 D:\DFPYME\htdocs\dfpyme\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('\r\n        SELEC...')
#4 D:\DFPYME\htdocs\dfpyme\app\Models\facturaVentaModel.php(25): CodeIgniter\Database\BaseConnection->query('\r\n        SELEC...')
#5 D:\DFPYME\htdocs\dfpyme\app\Controllers\consultas_y_reportes\duplicadoFacturaController.php(31): App\Models\facturaVentaModel->facturas_por_rango_de_fechas('2022-06-30', '')
#6 D:\DFPYME\htdocs\dfpyme\system\CodeIgniter.php(832): App\Controllers\consultas_y_reportes\duplicadoFacturaController->facturas_por_rango_de_fechas()
#7 D:\DFPYME\htdocs\dfpyme\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\consultas_y_reportes\duplicadoFacturaController))
#8 D:\DFPYME\htdocs\dfpyme\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 D:\DFPYME\htdocs\dfpyme\index.php(37): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2022-06-30 19:17:37 --> Call to a member function getResultArray() on bool
#0 D:\DFPYME\htdocs\dfpyme\app\Controllers\consultas_y_reportes\duplicadoFacturaController.php(31): App\Models\facturaVentaModel->facturas_por_rango_de_fechas('2022-06-30', '')
#1 D:\DFPYME\htdocs\dfpyme\system\CodeIgniter.php(832): App\Controllers\consultas_y_reportes\duplicadoFacturaController->facturas_por_rango_de_fechas()
#2 D:\DFPYME\htdocs\dfpyme\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\consultas_y_reportes\duplicadoFacturaController))
#3 D:\DFPYME\htdocs\dfpyme\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 D:\DFPYME\htdocs\dfpyme\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
ERROR - 2022-06-30 19:17:38 --> ErrorException: pg_query(): Query failed: ERROR:  la sintaxis de entrada no es válida para tipo date: «»
LINE 10:         fecha_factura_venta BETWEEN '2022-06-30' AND '';
                                                              ^ in D:\DFPYME\htdocs\dfpyme\system\Database\Postgre\Connection.php:135
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'D:\\DFPYME\\htdoc...', 135)
#1 D:\DFPYME\htdocs\dfpyme\system\Database\Postgre\Connection.php(135): pg_query(Resource id #122, '\r\n        SELEC...')
#2 D:\DFPYME\htdocs\dfpyme\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('\r\n        SELEC...')
#3 D:\DFPYME\htdocs\dfpyme\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('\r\n        SELEC...')
#4 D:\DFPYME\htdocs\dfpyme\app\Models\facturaVentaModel.php(25): CodeIgniter\Database\BaseConnection->query('\r\n        SELEC...')
#5 D:\DFPYME\htdocs\dfpyme\app\Controllers\consultas_y_reportes\duplicadoFacturaController.php(31): App\Models\facturaVentaModel->facturas_por_rango_de_fechas('2022-06-30', '')
#6 D:\DFPYME\htdocs\dfpyme\system\CodeIgniter.php(832): App\Controllers\consultas_y_reportes\duplicadoFacturaController->facturas_por_rango_de_fechas()
#7 D:\DFPYME\htdocs\dfpyme\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\consultas_y_reportes\duplicadoFacturaController))
#8 D:\DFPYME\htdocs\dfpyme\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 D:\DFPYME\htdocs\dfpyme\index.php(37): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2022-06-30 19:17:38 --> Call to a member function getResultArray() on bool
#0 D:\DFPYME\htdocs\dfpyme\app\Controllers\consultas_y_reportes\duplicadoFacturaController.php(31): App\Models\facturaVentaModel->facturas_por_rango_de_fechas('2022-06-30', '')
#1 D:\DFPYME\htdocs\dfpyme\system\CodeIgniter.php(832): App\Controllers\consultas_y_reportes\duplicadoFacturaController->facturas_por_rango_de_fechas()
#2 D:\DFPYME\htdocs\dfpyme\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\consultas_y_reportes\duplicadoFacturaController))
#3 D:\DFPYME\htdocs\dfpyme\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 D:\DFPYME\htdocs\dfpyme\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
